### ISSUE TITLE
Montar la infraestructura de desarrollo

### ISSUE THREAD

**Issue by JesusAparicioOrtiz** [JesusAparicioOrtiz/IBT#3]
Montar la infraestructura para el desarrollo del proyecto:

- [x] Crear una organización y un repositorio para el proyecto e invitar al profesor.
- [x] Crear el mongo en la nube.
- [x] Inicializar el proyecto con una plantilla para las tecnologías que queremos usar.
- [x] Preparar el backlog inicial en base a las historias del anteproyecto.
- [x] Instalar todas la plataformas necesarias.
- [x] Crear cuenta heroku para despliegue.
